### ISSUE TITLE
Create unl_buildings module

### ISSUE THREAD

**Issue by macburgee1** [unlcms/project-herbie#174]
A unl_buildings module will pull building data from https://maps.unl.edu/buildings?format=json and store a local copy for other modules to utilize.

One place where we want this data is for the Contact Info Block. We want to give users the ability to select a building, which will then link the building's address on the UNL Maps service.

**Where to store the data?**
When the buildings data is fetched, how should it be stored? Is it content? config? A custom table?

**How will data be retrieved?**
Should we provide a procedural functional? A class/method?

**How will data storage affect caching?**
In the event data is updated, how will cache be invalidated?

**How should the data be refreshed?**
Should the data be regularly refreshed as a cron job? Should we provide a manual refresh option?

**Initial thoughts**
I'm leaning toward a custom table to store the data. If we create a custom entity type/bundle - the entity type can be defined in code but bundles are config, so that creates more management. The data really isn't config. We'd have to ignore the config for sync purposes since it'll be prone to change on its own.

Regarding retrieval, I think we stick with OOP. Create a UnlMaps class with one or more retrieval methods (e.g. ::getBuildings() ).

Regarding caching, I'm not 100% sure. Here are my initial thoughts - define a cache tag to use, then clear that tag whenever the building data is updated. It'll be up to whoever is using the data to add the cache tag to their render array.

Regarding refreshing, I think we add a cron job that runs daily. There should also be an admin UI where an admin can see the current building data and where an admin can manually trigger a data refresh.

**Comment by macburgee1** [comment]
This issue is blocked until the JSON feed for UNL Maps app is fixed: https://maps.unl.edu/buildings?format=json

It's currently returning:
```
<br />
<b>Fatal error</b>:  Uncaught exception 'Savvy_TemplateException' with message 'Could not find the template UNL/TourMap/GoogleMap/City.tpl.php' in /var/www/html/maps/vendor/saltybeagle/savvy/src/Savvy.php:678
Stack trace:
#0 /var/www/html/maps/vendor/saltybeagle/savvy/src/Savvy.php(963): Savvy-&gt;findTemplateFile('UNL/TourMap/Goo...')
#1 /var/www/html/maps/vendor/saltybeagle/savvy/src/Savvy.php(922): Savvy-&gt;fetch(Object(UNL_TourMap_GoogleMap_City), NULL)
#2 /var/www/html/maps/vendor/saltybeagle/savvy/src/Savvy.php(731): Savvy-&gt;renderObject(Object(UNL_TourMap_GoogleMap_City), NULL)
#3 /var/www/html/maps/www/templates/json/UNL/TourMap.tpl.php(8): Savvy-&gt;render(Object(UNL_TourMap_GoogleMap_City), NULL)
#4 /var/www/html/maps/vendor/saltybeagle/savvy/src/Savvy.php(143): include('/var/www/html/m...')
#5 [internal function]: Savvy-&gt;basicOutputController(Object(UNL_TourMap), NULL, '/var/www/html/m...', Object(UNL_TourMap_OutputController))
#6 /var/www/html/maps/vendor/saltybeagle/savvy/src/Savvy.php(983): call_user_func(Array, Object(UNL_T in <b>/var/www/html/maps/vendor/saltybeagle/savvy/src/Savvy.php</b> on line <b>678</b><br />
```

**Comment by macburgee1** [comment]
We could also use ITS' API: https://its-api.unl.edu/static/v1/unl/maps/buildings.json
